pub mod compensation_panel;
pub mod edits;
pub mod gallery;
pub mod gate_rules_window;
pub mod gate_sidebar;
pub mod gates;
pub mod main_window;
pub mod pairing_controls;
mod parity_tests;
pub mod path_picker;
pub mod plots;
mod reactivity_tests;
pub mod review;
pub mod route;
pub mod workspace_window;
