pub mod compensation_panel;
pub mod edits;
pub mod gallery;
pub mod gate_rules_window;
pub mod gate_sidebar;
pub mod gates;
pub mod main_window;
pub mod pairing_controls;
mod parity_tests;
pub mod path_picker;
mod paused_run;
pub mod plots;
pub mod position_menu;
mod reactivity_tests;
pub mod review;
mod review_tests;
pub mod review_window;
pub mod route;
pub mod search_panel;
pub mod workspace_window;
